name: Run fbmkr.py on push

on:
  push:
    branches: [ "main" ]

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run fbmkr.py
        run: python fbmkr.py
